### ISSUE TITLE
i believe many of us PS users just use this tool to transfer PC save to PS4. So we dont even use the inventory editor functionality, but just the character import function. please consider releasing a hotfix to address the crash alone.

### ISSUE THREAD

**Issue by Eman0133** [ClayAmore/ER-Save-Editor#47]
Hey slayer, what do you mean Carlos complied it and you were able to transfer? I’m only trying to transfer from PC to PS5 as well and would love to do that as soon as possible!

**Comment by Ninjafartdust130** [comment]
Is it out a done yet or no

**Comment by Eman0133** [comment]
> Is it out a done yet or no

no, but some other person was able to compile source codes and other stuff to make it work. im having trouble doing it myself

**Comment by edgybravo** [comment]
> > Is it out a done yet or no
> 
> no, but some other person was able to compile source codes and other stuff to make it work. im having trouble doing it myself

Who's done it? where do I get this I just want to move pc character to ps4 and vise versa that's it.

**Comment by RinxAika** [comment]
I've had zero luck here with compiled version. Were you able to load PS4 and import your PC save to it? I can only open PC save

**Comment by Ninjafartdust130** [comment]
We want the inventory editor  get over it womp womp deal with it

**Comment by Eman0133** [comment]
Hey yall, so the compiled version, I was only able to move my ‘ Steam ‘ version of E.R. Over to my ps5. I since tried to move my ps5 save around, that will not work anymore! So be careful, I believe the, ‘Download’ link that @Carlos shared ( the compiled version) was only for a pre-dlc transfer PC - Ps5.  I was able to do only that.

**Comment by Eman0133** [comment]
> I've had zero luck here with compiled version. Were you able to load PS4 and import your PC save to it? I can only open PC save

I have not, only PC->PS5 for now.. check up ^

**Comment by CristianAxe** [comment]
@Eman0133 Can you share the steps you took to make it work?
I compiled my own version based on another topic here, the save from PC works, the save from PSX crashes it.

**Comment by Bubbuh-0** [comment]
> Hey yall, so the compiled version, I was only able to move my ‘ Steam ‘ version of E.R. Over to my ps5. I since tried to move my ps5 save around, that will not work anymore! So be careful, I believe the, ‘Download’ link that @carlos shared ( the compiled version) was only for a pre-dlc transfer PC - Ps5. I was able to do only that.

I have tried this and nothing works, any help?

**Comment by Eman0133** [comment]
> @Eman0133 Can you share the steps you took to make it work? I compiled my own version based on another topic here, the save from PC works, the save from PSX crashes it.

Yeah, so I only followed the instructions of the YouTubers who led me here. At first nothing was working, I used the download link that Carlos sent, in issue forum #37 i think. Using THAT link. I was able to transfer my Pc Save —> FlashDrive for ps4/5. Using SaveWizard and all. I have SINCE tried to copy my current Save file from ps5 ( the one I had FINALLY successfully transferred from pc) back onto the Editor. This crashes the platform just as before, it does still allow me to transfer my OLD ps5 save oddly. Including my original PC save. I can’t move my current ps5 save though and that will likely take Clayamors Update.

**Comment by lowryder2005** [comment]
@Eman0133 Do you have a copy of your original PS4 save, and would you be willing to share it? Specifically, the one you exported and that the 0.22 Save Manager was able to read initially. It could possibly be in the back-ups of SaveWizard.

Through testing, I've also concluded that the version of the original PS4 save might be the key factor with the build created by Carlos. Once we have a working save, it could just be a matter of pasting the desidered character over with 0.22 and re-importing it with SW. However, it seems that the tool doesn't function properly after the save has been modified once.

**Comment by yesdog96** [comment]
@lowryder2005 I'm fairly confident the calibration update messed something up too. I can't upload anything from a save I just created like 10 minutes ago.

**Comment by Figma77** [comment]
Greetings!
is it possible to transfer a PS4 save to PC using this editor ?

**Comment by OExSTir** [comment]
> Greetings! is it possible to transfer a PS4 save to PC using this editor ?

yes but it's broken now so let's wait for the creator to fix it

**Comment by klarkyson** [comment]
Hi all! I can provide some context as to what's going on here and what a potential fix would be! 

I have been able to fix this for my own use, and I will explain how to do so, but mind you this is a "duct-tape fix" and will require you make adjustments to the code and build the executable yourself.

---

First off, what's the issue here?

The main problem seems to be with how the program identifies the save wizard file format. When you load a file into the editor the program must first identify if the file is actually an elden ring save (either PC or playstation). If the program is unable to verify that the file is one of these two types it fails an assertation, which invokes a panic, which causes the program to crash.

As I'm sure you can guess by my explanation so far that's exactly what's happening. The current code in the master branch has a bug in it that causes [`is_ps_save_wizard`](https://github.com/ClayAmore/ER-Save-Editor/blob/014107f0ca1cff867b5f7565cb79d6684f9b35df/src/save/save.rs#L827) to fail to identify that the input file is a playstation file.

---

So what's the fix?

Well if I had a perfect solution I would've submitted a PR by now, but alas this isn't really my area of expertise. That said, I do have a pretty good idea of what specifically is wrong: the checksum calculation.

Seemingly every ps save wizard file has some fixed (constant / unchanged) data appended to the end of its contents. As far as I can tell the author is attempting to use a MD5 checksum to verify that an input file has this fixed data at the end and is therefore is a ps save wizard file. It appears the author got the starting point of where this fixed chunk of data starts wrong and thus the [checksum they're comparing against](https://github.com/ClayAmore/ER-Save-Editor/blob/014107f0ca1cff867b5f7565cb79d6684f9b35df/src/save/save.rs#L13) was calculated with variable data and therefore will not pass the comparison.

So the long term fix would be to figure out the correct starting point of that fixed data so that the correct checksum can be stored, calculated, and compared against.

I however don't know how to find this starting point. I would imagine the most surefire way is for multiple people to submit their ps save wizard file so that they can be compared to find where the unchanging data at the end starts. - Again, though, I can't stress enough that I'm very uneducated in this realm so maybe there's a better way to do this.

---

Okay, now as promised how can this be fixed short-term?

Just have the `is_ps_save_wizard` always return true:
```rust
pub fn is_ps_save_wizard(br: &mut BinaryReader) -> bool {
	true
}
```

Luckily, the flow of the program always does the PC file check first so as long as you use non-corrupt pc and ps-savewizard files this should work. The only thing you have to be careful about is passing a file that is not an elden ring save b/c this fix makes it so that every file is identified as the playstation file type.

Edit: If people wouldn't mind posting their save wizard file exports I can probably work towards finding the correct offset and submit a PR.

**Comment by yesdog96** [comment]
> Hi all! I can provide some context as to what's going on here and what a potential fix would be!
> 
> I have been able to fix this for my own use, and I will explain how to do so, but mind you this is a "duct-tape fix" and will require you make adjustments to the code and build the executable yourself.
> 
> First off, what's the issue here?
> 
> The main problem seems to be with how the program identifies the save wizard file format. When you load a file into the editor the program must first identify if the file is actually an elden ring save (either PC or playstation). If the program is unable to verify that the file is one of these two types it fails an assertation, which invokes a panic, which causes the program to crash.
> 
> As I'm sure you can guess by my explanation so far that's exactly what's happening. The current code in the master branch has a bug in it that causes [`is_ps_save_wizard`](https://github.com/ClayAmore/ER-Save-Editor/blob/014107f0ca1cff867b5f7565cb79d6684f9b35df/src/save/save.rs#L827) to fail to identify that the input file is a playstation file.
> 
> So what's the fix?
> 
> Well if I had a perfect solution I would've submitted a PR by now, but alas this isn't really my area of expertise. That said, I do have a pretty good idea of what specifically is wrong: the checksum calculation.
> 
> Seemingly every ps save wizard file has some fixed (constant / unchanged) data appended to the end of its contents. As far as I can tell the author is attempting to use a MD5 checksum to verify that an input file has this fixed data at the end and is therefore is a ps save wizard file. It appears the author got the starting point of where this fixed chunk of data starts wrong and thus the [checksum they're comparing against](https://github.com/ClayAmore/ER-Save-Editor/blob/014107f0ca1cff867b5f7565cb79d6684f9b35df/src/save/save.rs#L13) was calculated with variable data and therefore will not pass the comparison.
> 
> So the long term fix would be to figure out the correct starting point of that fixed data so that the correct checksum can be stored, calculated, and compared against.
> 
> I however don't know how to find this starting point. I would imagine the most surefire way is for multiple people to submit their ps save wizard file so that they can be compared to find where the unchanging data at the end starts. - Again, though, I can't stress enough that I'm very uneducated in this realm so maybe there's a better way to do this.
> 
> Okay, now as promised how can this be fixed short-term?
> 
> Just have the `is_ps_save_wizard` always return true:
> 
> ```rust
> pub fn is_ps_save_wizard(br: &mut BinaryReader) -> bool {
> 	true
> }
> ```
> 
> Luckily, the flow of the program always does the PC file check first so as long as you use non-corrupt pc and ps-savewizard files this should work. The only thing you have to be careful about is passing a file that is not an elden ring save b/c this fix makes it so that every file is identified as the playstation file type.
> 
> Edit: If people wouldn't mind posting their save wizard file exports I can probably work towards finding the correct offset and submit a PR.

Would it be possible for you to upload the file you made? I have zero scripting experience 😭

**Comment by klarkyson** [comment]
@yesdog96 I forked, applied the "duct-tape fix" I detailed above, and then created a build via github actions
https://github.com/klarkyson/ER-Save-Editor/releases/tag/v0.0.22-fix1

I intend to take this down once this is inevitably fixed in main.

**Comment by yesdog96** [comment]
> @yesdog96 I forked, applied the "duct-tape fix" I detailed above, and then created a build via github actions https://github.com/klarkyson/ER-Save-Editor-PS-Hotfix/releases/tag/v0.0.22-fix1
> 
> I intend to take this down once this is inevitably fixed in main.

This is definitely the "hotfix" many of us PS4 players have been waiting for until a main fix/update is released. Just did it and there's still the obvious jank of the main, but I was able to use my current save and import a couple characters. Thanks man.

**Comment by BastiKlein** [comment]
> @yesdog96 I forked, applied the "duct-tape fix" I detailed above, and then created a build via github actions https://github.com/klarkyson/ER-Save-Editor/releases/tag/v0.0.22-fix1
> 
> I intend to take this down once this is inevitably fixed in main.

Thanks for that. I was now at least able to open my PS4 savegame export the first time. Unfortunately I can't find a way to solve my case. I have a PS4 savegame and want to import that to my PC savegame to continue there. I can now open the PS4 savegame with the fix but it crashes when I want to open my PC savegame. With the original version I can open my PC savegame but it crashes when I try to open the PS4 savegame. Am I doing something wrong or does my case not work yet?

Thanks!

**Comment by klarkyson** [comment]
@BastiKlein I do not own a copy of Elden Ring for PC so the only saves I can test with are ones I can find online. From what I was able to try however I didn't have any issues with importing PS4 -> PC or PC -> PS4. Both PC and PS4 savegames seem to be working for me.

Are your PC and PS4 save files up to regulation (1.12.2)? If not you should first load them into regulation elden ring, re-save them, and then give the save editor a try.

**Comment by lowryder2005** [comment]
I still have the same issue of not being able to import the PC character into the same PS save I linked before, unfortunately. The Editor opens and allows me to do a few things, including the import, but it never actually saves the changes. Would anyone who has had any luck let me know if they're able to import the character in the first slot into a working memory.txt file that I can re-import via SaveWizard?

[MySave.zip](https://github.com/user-attachments/files/16059269/MySave.zip)

As a bonus you get an online legit file with all items, gestures, etc. from both the base game and the DLC, everything finished in the base game, and only the first two DLC bosses defeated. :)

**Comment by klarkyson** [comment]
@lowryder2005 I can confirm I was able to take the .sl2 save file in your zip and import the first character slot "Vaering" to my PS4 save successfully.

The only hiccup that occured was that when I loaded in I was spawned under the map and had to fast travel to a nearby site of grace.

So that's all to say I'm sorry I can't help you more, but everything seems to be working fine for me.

**Comment by lowryder2005** [comment]
Thank you so much! Do you think you could reshare the entire CUSA folder? This way I can
just resign it with SW, I guess. It will spare me a headache... T_T

Il giorno mar 2 lug 2024 alle ore 00:08 klarkyson ***@***.***>
ha scritto:

**Comment by BastiKlein** [comment]
> @BastiKlein I do not own a copy of Elden Ring for PC so the only saves I can test with are ones I can find online. From what I was able to try however I didn't have any issues with importing PS4 -> PC or PC -> PS4. Both PC and PS4 savegames seem to be working for me.
> 
> Are your PC and PS4 save files up to regulation (1.12.2)? If not you should first load them into regulation elden ring, re-save them, and then give the save editor a try.

That actually worked!
Thank you. Very much appreciated!

**Comment by lowryder2005** [comment]
> > @BastiKlein I do not own a copy of Elden Ring for PC so the only saves I can test with are ones I can find online. From what I was able to try however I didn't have any issues with importing PS4 -> PC or PC -> PS4. Both PC and PS4 savegames seem to be working for me.
> > Are your PC and PS4 save files up to regulation (1.12.2)? If not you should first load them into regulation elden ring, re-save them, and then give the save editor a try.
> 
> That actually worked! Thank you. Very much appreciated!

Could you share your 1.12.2 PS4 save? I think the original one I'm using is corrupted and doesn't allow me to import my PC character. I've been desperate to find a save just to use it as a base to import the character over.

**Comment by klarkyson** [comment]
@lowryder2005 I'm guessing by the footer of your email reply that you're European. Perhaps you're having issues b/c the PS4 save you're using needs to be the north american region? (I don't know if this is true, just troubleshooting)

**Comment by lowryder2005** [comment]
> @lowryder2005 I'm guessing by the footer of your email reply that you're European. Perhaps you're having issues b/c the PS4 save you're using needs to be the north american region? (I don't know if this is true, just troubleshooting)

Hi again, klarkyson. You're correct, I'm EU-based. I'm not too sure if that could be a factor because (hypothetically) the saves for Elden Ring are not tied to the region(s); I imported and re-signed a US save via SaveWizard in the past with no issue. Then again, I don't know the inner workings of the editor.

The problem so far is just that no build of the ER Save Editor allows me to overwrite the PS4 save with the PC character (opening the exported PS4 file that needs to be rewritten is a bit wonky too). If I had to guess, I think it could be related to the fact that I downloaded a (heavily) modded save with an ungodly amount of items since it was the only PS4 one I could find with the right version that the editor could read. That's the save I shared as MySave.zip before in this same thread. I think the editor just has issues working with that specific save, despite it being the right version.

Sadly, I have only a physical copy of ER (PS5). If it were digital, I could just download the PS4 version and do it myself, I guess.

**Comment by BastiKlein** [comment]
> Could you share your 1.12.2 PS4 save? I think the original one I'm using is corrupted and doesn't allow me to import my PC character. I've been desperate to find a save just to use it as a base to import the character over.

Hi, sure. I attached the one that worked for me with the fix.
Hope it helps.

[memory1.zip](https://github.com/user-attachments/files/16074965/memory1.zip)

**Comment by sindhudhairya** [comment]
Hi, is this fix to bypass the crash caused by the dlc? I am assuming I can not add dlc items until an update is made by the author? @yesdog96

**Comment by lowryder2005** [comment]
> > Could you share your 1.12.2 PS4 save? I think the original one I'm using is corrupted and doesn't allow me to import my PC character. I've been desperate to find a save just to use it as a base to import the character over.
> 
> Hi, sure. I attached the one that worked for me with the fix. Hope it helps.
> 
> [memory1.zip](https://github.com/user-attachments/files/16074965/memory1.zip)

You are amazing, thank you! This is exactly what I needed. I've finally been able to import the character over this. If there's anything I can do in-game to help you do let me know. :)

**Comment by spookyschmack** [comment]
> @yesdog96 I forked, applied the "duct-tape fix" I detailed above, and then created a build via github actions https://github.com/klarkyson/ER-Save-Editor/releases/tag/v0.0.22-fix1
> 
> I intend to take this down once this is inevitably fixed in main.

Hello everyone! I've included some files I developed, I have created some save files with max of EVERY item, two max level DLC weapons, with DLC unlocked and many graces unlocked in the DLC area, the saves have literally everything and have been tested online on multiple accounts. Hope it helps anyone, I was able to successfully get all DLC items on Playstation using SaveWizard.

Here's the mod page with more details:
[https://www.nexusmods.com/eldenring/mods/5449](https://www.nexusmods.com/eldenring/mods/5449)

[Elden Ring Ultimate PVP Base Character - Low Level PVP.zip](https://github.com/user-attachments/files/16077083/Elden.Ring.Ultimate.PVP.Base.Character.-.Low.Level.PVP.zip)
[Elden Ring Ultimate PVP Base Character - High Level PVP.zip](https://github.com/user-attachments/files/16077086/Elden.Ring.Ultimate.PVP.Base.Character.-.High.Level.PVP.zip)
[10Characters8MaxLevelWeapons2LowLevel.zip](https://github.com/user-attachments/files/16077091/10Characters8MaxLevelWeapons2LowLevel.zip)

**Comment by BastiKlein** [comment]
> > > Could you share your 1.12.2 PS4 save? I think the original one I'm using is corrupted and doesn't allow me to import my PC character. I've been desperate to find a save just to use it as a base to import the character over.
> 
> > 
> 
> > Hi, sure. I attached the one that worked for me with the fix. Hope it helps.
> 
> > 
> 
> > [memory1.zip](https://github.com/user-attachments/files/16074965/memory1.zip)
> 
> 
> 
> You are amazing, thank you! This is exactly what I needed. I've finally been able to import the character over this. If there's anything I can do in-game to help you do let me know. :)

You're welcome. I'm happy to help other players here as they helped me with the transfer from PS4 to PC :)

**Comment by SatanaPayalnik** [comment]
please, someone help me decrypt the save from ps4, version 1.10

**Comment by twp2000** [comment]
idk what im doing help...

**Comment by mlxzlas** [comment]
> > @yesdog96 I forked, applied the "duct-tape fix" I detailed above, and then created a build via github actions https://github.com/klarkyson/ER-Save-Editor/releases/tag/v0.0.22-fix1
> > I intend to take this down once this is inevitably fixed in main.
> 
> Hello everyone! I've included some files I developed, I have created some save files with max of EVERY item, two max level DLC weapons, with DLC unlocked and many graces unlocked in the DLC area, the saves have literally everything and have been tested online on multiple accounts. Hope it helps anyone, I was able to successfully get all DLC items on Playstation using SaveWizard.
> 
> Here's the mod page with more details: https://www.nexusmods.com/eldenring/mods/5449
> 
> [Elden Ring Ultimate PVP Base Character - Low Level PVP.zip](https://github.com/user-attachments/files/16077083/Elden.Ring.Ultimate.PVP.Base.Character.-.Low.Level.PVP.zip) [Elden Ring Ultimate PVP Base Character - High Level PVP.zip](https://github.com/user-attachments/files/16077086/Elden.Ring.Ultimate.PVP.Base.Character.-.High.Level.PVP.zip) [10Characters8MaxLevelWeapons2LowLevel.zip](https://github.com/user-attachments/files/16077091/10Characters8MaxLevelWeapons2LowLevel.zip)


Hi there, thanks for the work first, you provide 3 files, the last one is a txt file, how do I use them?

**Comment by yesdog96** [comment]
> @yesdog96 I forked, applied the "duct-tape fix" I detailed above, and then created a build via github actions https://github.com/klarkyson/ER-Save-Editor/releases/tag/v0.0.22-fix1
> 
> I intend to take this down once this is inevitably fixed in main.

Hey @klarkyson any thoughts on how to fix the hotfix for post patch 1.13? Any save PC or PS4 crashes the editor

**Comment by wenjian-zhou** [comment]
> @yesdog96 I forked, applied the "duct-tape fix" I detailed above, and then created a build via github actions https://github.com/klarkyson/ER-Save-Editor/releases/tag/v0.0.22-fix1
> 
> I intend to take this down once this is inevitably fixed in main.

Hi @klarkyson any progress on the new patch 1.13? The saves will crash now.

**Comment by ClayAmore** [comment]
I understand. This is part of the reason why this is open source so I don't have be obligated to make sub tools to cater to specific needs. I needed to redo the parser properly. As it was I left a bunch of things undone when I did the first time. The new release is hopefully gonna be more stable and future proof.

**Comment by EFT92** [comment]
I'm looking to transfer my Steam save over to my PS5. I only have the PS5 disc version and no the PS4 version. Is this possible and can someone help me with how to do this. Thanks

**Comment by EFT92** [comment]
> Hey yall, so the compiled version, I was only able to move my ‘ Steam ‘ version of E.R. Over to my ps5. I since tried to move my ps5 save around, that will not work anymore! So be careful, I believe the, ‘Download’ link that @carlos shared ( the compiled version) was only for a pre-dlc transfer PC - Ps5. I was able to do only that.

I'm looking to transfer my Steam save over to my PS5. I only have the PS5 disc version and no the PS4 version. Is this possible and can you help me with how to do this. Thanks

**Comment by mgibson041387** [comment]
For those who do not want to download the exe and run on system you can use the web based version found at the following link. It is a fork off the source found here on the developers git repo and the crashing has been fixed. Works exactly like the compiled version found on this repo. Full credit for the development of this program goes to the original dev, i just tweeked it a bit to work as a webpage and added a quick cheat tab for slight ease of use.

https://mgibson041387.github.io/ER-Save-Editor/

**Comment by yo-repo87** [comment]
For those who do not want to download the exe and run on system you can use the web based version found at the following link. It is a fork off the source found here on the developers git repo and the crashing has been fixed. Works exactly like the compiled version found on this repo. Full credit for the development of this program goes to the original dev, i just tweeked it a bit to work as a webpage and added a quick cheat tab for slight ease of use. Full list of added features and bug fixes can be found below.

https://yo-repo87.github.io/ER-Save-Editor

**Here's the full list of features added to this project:**

Save format / platform support
- Raw PlayStation (PS4) save read/write support, detected by magic bytes independent of file extension
- WASM/web build target (separate from native) with its own theming
- Docker-based self-hosted web deployment (selfhosted.vip/er-save-editor)
- GitHub Pages deployment on mgibson041387/ER-Save-Editor, with an Actions workflow that auto-builds and redeploys on every push to master
- A second, identical GitHub Pages deployment on yo-repo87/ER-Save-Editor

Inventory
- Item quantity editing and weapon upgrade-level editing from the Browse screen (edit popup)
- Item removal (single item and "Clear All Inventory")
- Wiki link + item image lookup for inventory items

Quick Cheats (new top-level screen)
- Souls: +1k/+10k/+50k/+100k/+500k/+1M/+10M buttons, plus Max (999,999,999)
- Stats: Max All Stats (sets all 8 attributes to 99)
- Rune Arcs: +1/+5/+10/+99 buttons
- Flasks: Max Out Flask Charges (tops off held Crimson/Cerulean flasks to their current upgrade level's cap)
- Unlocks: one-click bulk grant for Weapons, Armor, Talismans, Ashes of War, Spells, Crafting Materials, Consumables, Bell Bearings, Crystal Tears, Spirit Ashes, and Sites of Grace

Stats page
- Press/hold < > buttons on each attribute for in-game-style ±1 stepping with auto-repeat

**Confirmed against the code. Here's the accurate list of genuine bug fixes made to the original (upstream ClayAmore/ER-Save-Editor) source:**

Crash/panic fixes (malformed or edge-case data that used to bring down the whole app):

1. src/util/validator.rs:55 — Validating a weapon's Ash of War used a raw HashMap index that panicked if the gaitem handle had no match (e.g. a hand-edited save with a dangling AoW reference). Now returns a proper Err instead of crashing.
2. src/vm/vm.rs:147-149 — HP/FP/SP table lookups indexed directly by Vigor/Mind/Endurance with no bounds check, panicking if a stat exceeded the table length. Now clamped with .min(len - 1).
3. src/vm/vm.rs:211, 244 — Somber-to-normal weapon upgrade-level lookup panicked on unmapped weapon IDs. Now falls back to 0 via .unwrap_or(&0).
4. src/save/common/save_slot.rs:1248 — The gender byte was read with no validation; anything other than 0/1 now returns a descriptive error instead of silently misbehaving (or previously crashing elsewhere downstream).
5. src/util/bnd4.rs, src/util/params.rs, src/util/regulation.rs — Systematic pattern: parsing code for the BND4 container, PARAM headers, and regulation/DCX headers used assert_eq!/unwrap(), which panicked on any malformed or unexpected input. Converted throughout to Result-returning error paths.

Incorrect assumption fixes:

6. src/save/common/user_data_11.rs — Upstream asserted the first byte of a rest field was always 0; that assumption was wrong and caused real, legitimate saves to be rejected. The assertion was removed (test comment: "A prior version asserted rest[0] == 0, which turned out to be an unfounded assumption").
7. src/save/save.rs (is_ps) — Raw PlayStation saves (magic CB 01 9C 2C) were never checked for at all — Save::is() only recognized PC saves and Save-Wizard-exported PS saves, so a real user's raw PS4 save was rejected outright as "not a recognized Elden Ring save." Added the missing magic-byte check.
